# config/abm_sweep.yaml

experiment: "abm_parameter_sweep"

sweep: 
  n_steps: 1500 # 150 minutes
  result_dir: "ABM_RESULT_DIR"

# Range of values with parameters
param_ranges: 
  f_magnitude: [8.0, 10.0, 12.0, 14.0]
  rhoa_k_gain: [8.0, 10.0, 12.0, 15.0]
  rhoc_protrusion_gain: [3.0, 4.0, 5.0, 6.0]

# Experiment AR targets for scoring
exp_targets: 
  WT: 5.403
  DSP_KO: 7.047
  TJP1_KO: 3.371
  DSP_JCAD_DKO: 6.224
  TJP1_JCAD_DKO: 4.040

# Ordering Constraints
ordering_constraints:
  - [TJP1_KO, WT]
  - [WT, DSP_KO]
  - [DSP_JCAD_DKO, DSP_KO]
  - [TJP1_KO, TJP1_JCAD_DKO]
