# config/ bm_sim.yaml

# Metadata
experiment: "bm_perturbation_simulation"

# Path Configuration
model:
  bnd: "rho.bnd"
  cfg: "rho.cfg"
  bnd_v1: "maboss_models/rho.bnd"
  bnd_v2: "maboss_models/rho_v2.bnd"
  cfg_v3: "maboss_models/rho_v3.cfg"
  cfg_v4: "maboss_models/rho_v4.cfg"


# Sim Settings
simulation: 
  max_time: 10.0
  sample_count: 5000

# Analysis Settings
analysis:
  nodes:
    target_a: "RhoA"
    target_b: "RhoC"
  eps: 0.25
  phenotypes:
    failed: "Failed"
    normal: "Normal"
    hyper: "Hyper"

# Perturbation Settings
perturbations:
  WT:  {}
  DSP_KO: {DSP: "OFF"}
  TJP1_KO: {TJP1: "OFF"}
  JCAD_KO: {JCAD: "OFF"}
  DSP_JCAD_DKO: {DSP: "OFF", JCAD: "OFF"}
  TJP1_JCAD_DKO: {TJP1: "OFF", JCAD: "OFF"}
