# config/ bm_sweep.yaml

# Metadata
experiment: "bm_parameter_sweep"

ranges:
  amp:          { start: 0.0, stop: 50.0, step: 2.5 }
  mod:          { start: 0.0, stop: 5.5,  step: 0.25 }
  basal:        { start: 0.0, stop: 1.5, step: 0.2 }
  antagonistic: { start: 0.0, stop: 16.0, step: 1.0 }
  decay:        { start: 0.0, stop: 1.1, step: 0.1 }
  recruitment:  { start: 0.0, stop: 1.1, step: 0.1 }

groups:
  rhos: ["RhoA", "RhoC"]
  junctions:  ["DSP", "TJP1", "JCAD"]

lut:
    resolution: "coarse"
    parameters: ["$DSP_recruitment", "$TJP1_recruitment", "$JCAD_recruitment"]
    
sweeps: 
  # --- 1D Sweeps ---
  - name: "wt_sweep"
    perturbations: ["WT"]
    type: "1D"
    resolution: "fine"
    parameters: "all"

  - name: "dsp_sweep"
    perturbations: ["DSP_KO"]
    type: "1D"
    resolution: "fine"
    parameters: ["$RhoC_antagonistic", "$RhoC_mod", "$RhoC_amp", "$RhoC_decay"]

  - name: "tjp1_sweep"
    perturbations: ["TJP1_KO"]
    type: "1D"
    resolution: "fine"
    parameters: ["$RhoA_antagonistic", "$RhoA_mod", "$RhoA_amp", "$RhoA_decay"]

  - name: "jcad_sweep"
    perturbations: ["JCAD_KO"]
    type: "1D"
    resolution: "fine"
    parameters: ["$RhoA_mod", "$RhoC_mod", "$RhoA_basal", "$RhoC_basal"]

  - name: "DSP_JCAD_Sweep"
    perturbations: ["DSP_JCAD_DKO"]
    type: "1D"
    resolution: "fine"
    parameters: ["$RhoC_mod", "$RhoC_basal", "$RhoA_basal"]

  - name: "TJP1_JCAD_Sweep"
    perturbations: ["TJP1_JCAD_DKO"]
    type: "1D"
    resolution: "fine"
    parameters: ["$RhoA_mod", "$RhoA_basal", "$RhoC_basal"]

  - name: "DSP_TJP1_Sweep"
    perturbations: ["DSP_TJP1_DKO"]
    type: "1D"
    resolution: "fine"
    parameters: ["$RhoA_basal", "$RhoC_basal"]

  # --- 2D Sweeps ---
  - name: "Competition_Landscape"
    perturbations: ["WT", "TJP1_KO", "DSP_KO"]
    type: "2D"
    resolution: "coarse"
    parameters: ["$RhoA_antagonistic", "$RhoC_antagonistic"]
  - name: "Escape_Threshold_RhoA"
    perturbations: ["WT", "TJP1_KO"]
    type: "2D"
    resolution: "coarse"
    parameters: ["$RhoA_amp", "$RhoA_antagonistic"]
  - name: "Escape_Threshold_RhoC"
    perturbations: ["WT", "DSP_KO"]
    type: "2D"
    resolution: "coarse"
    parameters: ["$RhoC_amp", "$RhoC_antagonistic"]

  - name: "Amplification_Gain_RhoA"
    perturbations: ["WT", "JCAD_KO", "TJP1_JCAD_DKO"]
    type: "2D"
    resolution: "coarse"
    parameters: ["$RhoA_amp", "$RhoA_mod"]
  - name: "Amplification_Gain_RhoC"
    perturbations: ["WT", "JCAD_KO", "DSP_JCAD_DKO"]
    type: "2D"
    resolution: "coarse"
    parameters: ["$RhoC_amp", "$RhoC_mod"]

  - name: "Moderate_Gain_RhoA"
    perturbations: ["WT", "JCAD_KO", "TJP1_JCAD_DKO"]
    type: "2D"
    resolution: "coarse"
    parameters: ["$RhoA_mod", "$RhoA_basal"]
  - name: "Moderate_Gain_RhoC"
    perturbations: ["WT", "JCAD_KO", "DSP_JCAD_DKO"]
    type: "2D"
    resolution: "coarse"
    parameters: ["$RhoC_mod", "$RhoC_basal"]
  
  - name: "basal_activity_robustness"
    perturbations: ["WT"]
    type: "2D"
    resolution: "coarse"
    parameters: ["$RhoA_basal", "$RhoC_basal"]


