# Metadata
experiment: "perturbation_simulation"

# Path Configuration
model:
  bnd: "models/rho.bnd"
  cfg_v3: "models/rho_v3.cfg"

  

# Analysis Settings
analysis:
  nodes:
    target_a: "RhoA"
    target_b: "RhoC"
  eps: 0.25
  phenotypes:
    failed: "Failed"
    normal: "Normal"
    hyper: "Hyper"

# Perturbation Settings
perturbations:
  WT:  {}
  DSP_KO: {DSP: "OFF"}
  TJP1_KO: {TJP1: "OFF"}
  JCAD_KO: {JCAD: "OFF"}
  DSP_JCAD_DKO: {DSP: "OFF", JCAD: "OFF"}
  TJP1_JCAD_DKO: {TJP1: "OFF", JCAD: "OFF"}
