# Config for spatial model aspects

# Lookup Table Configuration
files: 
  recruitment_csv: "param_sweep_Recruitment_Sweep.csv"

recruitment_var_maps: {'$DSP_recruitment': 'p_dsp', '$TJP1_recruitment': 'p_tjp1', '$JCAD_recruitment': 'p_jcad'}

# Protein-Specifc Hill Parameters
hill_params: 
  # K: Activation Threshold: Tension level where junction is stressed enough to signal
  # n: Cooperativity
  JCAD: {K: 1.5, n: 3}
  DSP: {K: 1.5, n: 3}
  TJP1: {K: 1.5, n: 3}

# Rho to Mechanics Mapping Constants
meachanics: 
  k_base: 1.0
  kc_ratio: 0.1         # Bilinear: 10% stiffness in compression
  rhoa_k_mult: 4.0      # How much RhoA stiffens the spring
  rhoa_l_shrink: 0.5    # How much RhoA contracts the rest length (failed elongation)
  rhoc_l_shrink: 0.4    # RhoC-driven contraction (hyper elongation)
  