# Config for spatial model aspects

# Lookup Table Configuration
files: 
  recruitment_csv: "param_sweep_Joint_Recr_Sweep.csv"

sim: 
  dt: 0.1
  gamma: 1.0 # viscuous drag (higher ≈ slower movement)


# Parameter for tension calculation
mechanics:
  k_area: 0.8 # Area conservation stiffness
  k_spring: 1.0 # Permanent / Basal stiffness of springs (actin filaments)

  tau_remodel: 20.0 # Relaxation time
  rhoa_k_gain: 3.0 # How much RhoA stiffens cortex
  rhoa_l_shrink: 0.2 # General Contraction from RhoA
  rhoc_l_shrink: 0.5 # General contraction from RhoC
  kc_ratio: 0.1 # Bilinear: 10% stiffness in compression
 
# Protein-Specifc Hill Parameters
hill_params: 
  # K: Activation Threshold: Tension level where junction is stressed enough to signal
  # n: Cooperativity
  JCAD: {K: 1.5, n: 3}
  DSP: {K: 1.5, n: 3}
  TJP1: {K: 1.5, n: 3}
  